services:
  doera:
    build: ./
    container_name: doera
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__SqlConnection=Server=db;Database=DoeraDatabase;User Id=sa;Password=DoLiGenT123!;TrustServerCertificate=True
      - ElmahIo__ApiKey=
      - ElmahIo__LogId=
      - SendGrid__ApiKey=
      - Serilog__Using__0=Serilog.Sinks.Console
      - Serilog__Using__1=Elastic.Serilog.Sinks
      - Serilog__MinimumLevel__Default=Debug
      - Serilog__WriteTo__0__Name=Console
      - Serilog__WriteTo__1__Name=Elasticsearch
      - Serilog__WriteTo__1__Args__bootstrapMethod=Silent
      - Serilog__WriteTo__1__Args__nodes__0=http://elasticsearch:9200
      - Serilog__WriteTo__1__Args__dataStream=logs-doera-default
    volumes:
      - dataprotection:/root/.aspnet/DataProtection-Keys

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=DoLiGenT123!
    volumes:
      - mssqldata:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P DoLiGenT123! -Q 'SELECT 1' -C"]
      interval: 10s
      retries: 10
      start_period: 20s

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.19.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -sSf http://localhost:9200/_cluster/health?wait_for_status=yellow || exit 1"]
      interval: 10s
      retries: 20
      start_period: 60s

  kibana:
    image: docker.elastic.co/kibana/kibana:8.19.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_HOST=0.0.0.0
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -sSf http://localhost:5601/api/status || exit 1"]
      interval: 10s
      retries: 10
      start_period: 20s

volumes:
  mssqldata:
  dataprotection:
  esdata: